# Generated by Django 5.1 on 2024-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram User ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Telegram Chat ID')),
                ('username', models.CharField(max_length=64, null=True, verbose_name='Telegram Username')),
            ],
            options={
                'db_table': 'tg_user',
            },
        ),
    ]
