version: '3'

volumes:
  pg_data:
  static:
  media:
  pgadmin:

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  django:
    build: ./django_adrf_aiogram/
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - redis
  celery:
    build: ./django_adrf_aiogram/
    command: celery -A app.delivery.web worker -l info
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - redis
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - django
      - db
  # pgadmin:
  #   image: dpage/pgadmin4:8
  #   environment:
  #     - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
  #     - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
  #   ports:
  #     - 5050:80
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   depends_on:
  #     - db
